port: 9111

hippo:
  url: rmi://localhost:1099/hipporepository
  username:
  password:

datasource:
  url: jdbc:postgresql://localhost:5432/publications
  username: publications
  password: publications
  databaseName: publications
  serverName: publications
  user: publications
  URL: jdbc:postgresql://localhost:5432/publications
  maxPoolSize: 2

s3:
  bucket:
  key:
  secret:
  path:
