port: 9111

hippo:
  url: rmi://localhost:1099/hipporepository
  user:
  password:

datasource:
  url: jdbc:postgresql://localhost:5432/publications
  username:
  password:
  maxPoolSize: 10

s3:
  bucketName:
  key:
  secret:
  path:
