#!/bin/sh

adduser \
  --quiet \
  --system \
  --home /opt/publications \
  --no-create-home \
  --shell /bin/bash \
  --group \
  --gecos "Publications" \
  publications

systemctl daemon-reload
systemctl enable publications
systemctl start publications