#!/bin/sh
. /etc/profile
set -eu

exec ${JAVA_HOME:-/usr}/bin/java \
  -Dlogback.configurationFile=/opt/publications/logback.xml \
  -jar /opt/publications/publications.jar "$@" | \
  logger --size 4KB -t publications
