#!/bin/sh
#JAVA=${JAVA_HOME:-/usr}/bin/java
JAVA=/usr/lib/jvm/java-17-openjdk-arm64/bin/java
. /etc/profile
set -eu

exec ${JAVA} \
  -Dlogback.configurationFile=/opt/publications/logback.xml \
  -XX:+UseParallelGC \
  -XX:GCTimeRatio=10 \
  -XX:MinHeapFreeRatio=20 \
  -XX:MaxHeapFreeRatio=40 \
  -jar /opt/publications/publications.jar "$@" | \
  logger --size 16KB -t publications
